# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "scarab"
license = "MIT"
licenselink = ""
description = "An even simpler theme for academic websites."
homepage = "https://github.com/jweisber/scarab"
tags = ["academic", "basic"]
features = ["posts", "publications", "social"]
min_version = 0.18

[author]
  name = "Jonathan Weisberg"
  homepage = "http://jweisber.github.io/"
